stages:
 - build
 - test

build1:
  stage: build
  script:
    - echo "***********************start building***********************"
    - echo $CI_COMMIT_BRANCH
    - cd /home/gitlab-runner/build
    - ./make_utd_builds.sh $CI_COMMIT_BRANCH $CI_PROJECT_NAME
    - echo "***********************start burning***********************"
    - cp -rf /home/gitlab-runner/build/up_to_date_builds/out_builds/ /home/gitlab-runner/version/$CI_COMMIT_SHA/
    - python3 ./flash.py
    - echo "***********************test prepare***********************"
    - cd /home/gitlab-runner/Documents/AutoTest/config
    - python3 ./config.py -b $CI_COMMIT_BRANCH -o $CI_PROJECT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^.*3\.0\..*/ || $CI_COMMIT_BRANCH =~ /^.*3\.1\..*/ || $CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never

test_sta:
  stage: test
  script:
    - echo "***********************STA TEST START***********************"
    - cd /home/gitlab-runner/Documents/AutoTest/Testcases
    - python3 ./CI_TEST_STA.py
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^.*3\.0\..*/ || $CI_COMMIT_BRANCH =~ /^.*3\.1\..*/ || $CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never

test_ap:
  stage: test
  script:
    - echo "***********************AP TEST START***********************"
    - cd /home/gitlab-runner/Documents/AutoTest/Testcases
    - python3 ./CI_TEST_AP.py
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^.*3\.0\..*/ || $CI_COMMIT_BRANCH =~ /^.*3\.1\..*/ || $CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
    
test_BLE:
  stage: test
  script:
    - echo "***********************BLE TEST START***********************"
    - cd /home/gitlab-runner/Documents/AutoTest/Testcases
    - python3 ./CI_TEST_BLE.py
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^.*3\.0\..*/ || $CI_COMMIT_BRANCH =~ /^.*3\.1\..*/ || $CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never

